# Liste complète des caisses régionales Crédit Agricole
# Clé = identifiant interne, Valeur = (nom affiché, URL du site régional)
CA_REGIONS: dict[str, tuple[str, str]] = {
    "ca-alsace-vosges": ("CA Alsace Vosges", "www.ca-alsace-vosges.fr"),
    "ca-anjou-maine": ("CA Anjou Maine", "www.ca-anjou-maine.fr"),
    "ca-aquitaine": ("CA Aquitaine", "www.ca-aquitaine.fr"),
    "ca-atlantique-vendee": ("CA Atlantique Vendée", "www.ca-atlantique-vendee.fr"),
    "ca-briepicardie": ("CA Brie Picardie", "www.ca-briepicardie.fr"),
    "ca-centrest": ("CA Centre Est", "www.ca-centrest.fr"),
    "ca-centre-france": ("CA Centre France", "www.ca-centre-france.fr"),
    "ca-centre-loire": ("CA Centre Loire", "www.ca-centre-loire.fr"),
    "ca-centre-ouest": ("CA Centre Ouest", "www.ca-centre-ouest.fr"),
    "ca-champagne-bourgogne": ("CA Champagne Bourgogne", "www.ca-champagne-bourgogne.fr"),
    "ca-charente-maritime-deux-sevres": ("CA Charente-Maritime Deux-Sèvres", "www.ca-cm2s.fr"),
    "ca-charente-perigord": ("CA Charente Périgord", "www.ca-charente-perigord.fr"),
    "ca-corse": ("CA Corse", "www.ca-corse.fr"),
    "ca-des-savoie": ("CA Des Savoie", "www.ca-des-savoie.fr"),
    "ca-finistere": ("CA Finistère", "www.ca-finistere.fr"),
    "ca-franche-comte": ("CA Franche-Comté", "www.ca-franchecomte.fr"),
    "ca-guadeloupe": ("CA Guadeloupe", "www.ca-guadeloupe.fr"),
    "ca-ille-et-vilaine": ("CA Ille-et-Vilaine", "www.ca-illeetvilaine.fr"),
    "ca-languedoc": ("CA Languedoc", "www.ca-languedoc.fr"),
    "ca-loirehauteloire": ("CA Loire Haute-Loire", "www.ca-loirehauteloire.fr"),
    "ca-lorraine": ("CA Lorraine", "www.ca-lorraine.fr"),
    "ca-martinique-guyane": ("CA Martinique Guyane", "www.ca-martinique.fr"),
    "ca-morbihan": ("CA Morbihan", "www.ca-morbihan.fr"),
    "ca-nord-de-france": ("CA Nord de France", "www.ca-nord-de-france.fr"),
    "ca-nord-est": ("CA Nord Est", "www.ca-nord-est.fr"),
    "ca-nord-midi-pyrenees": ("CA Nord Midi-Pyrénées", "www.ca-nmp.fr"),
    "ca-normandie": ("CA Normandie", "www.ca-normandie.fr"),
    "ca-normandie-seine": ("CA Normandie-Seine", "www.ca-normandie-seine.fr"),
    "ca-paris": ("CA d'Île-de-France (Paris)", "www.ca-paris.fr"),
    "ca-pca": ("CA Provence Côte d'Azur", "www.ca-pca.fr"),
    "ca-pyrenees-gascogne": ("CA Pyrénées Gascogne", "www.ca-pyrenees-gascogne.fr"),
    "ca-reunion": ("CA de La Réunion", "www.ca-reunion.fr"),
    "ca-rhone-alpes": ("CA Rhône Alpes", "www.ca-rhonealpes.fr"),
    "ca-sud-rhone-alpes": ("CA Sud Rhône-Alpes", "www.ca-sud-rhonealpes.fr"),
    "ca-toulouse31": ("CA Toulouse 31", "www.ca-toulouse31.fr"),
    "ca-touraine-poitou": ("CA Touraine Poitou", "www.ca-tourainepoitou.fr"),
    "ca-val-de-france": ("CA Val de France", "www.ca-valdefrance.fr"),
}
